#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/${0##*/}.conf

USB_ID="0bdb:1900"

RFKILL_DEVICE=$(for n in /sys/devices/platform/thinkpad_acpi/rfkill/rfkill*; do if [ "$(cat $n/name)" = "tpacpi_wwan_sw" ]; then echo $n/state; fi; done)

CONTROL_DEVICE () {
	echo /dev/$(for n in /sys/class/tty/ttyACM*/device/interface; do if [ "$(cat $n)" = "Ericsson F3507g Mobile Broadband Minicard Data Modem" ]; then echo $n|awk -F '/' '{print $5}'; fi; done)
}

case "$1" in
  start)
    stat_busy "Starting wwan connection"
	echo 1 > $RFKILL_DEVICE
	while [ -z "$(lsusb -d $USB_ID)" ] ; do sleep 0.5 ; done
	stat_append " : RFKILL"
	sleep 3
	/usr/sbin/chat -v "" "AT+CPIN=\"$PIN"\" > $(CONTROL_DEVICE) < $(CONTROL_DEVICE)
	stat_append " : PIN"
	sleep 2
	/usr/sbin/chat -v "" "AT+CFUN=1" >  $(CONTROL_DEVICE) < $(CONTROL_DEVICE)
	stat_append " : MODE"
	sleep 15
	/usr/sbin/chat -v "" "AT+CGDCONT=1,\"IP\",\"$APN\""> $(CONTROL_DEVICE) < $(CONTROL_DEVICE)
	stat_append " : APN"
	sleep 8
	/usr/sbin/chat -v "" "AT*ENAP=1,1" > $(CONTROL_DEVICE) < $(CONTROL_DEVICE)
	stat_append " : ETH"
    add_daemon wwan
    stat_done
    ;;
  stop)
    stat_busy "Stopping wwan Daemon"
	/usr/sbin/chat -v "" "AT*ENAP=0" "OK" > $(CONTROL_DEVICE) < $(CONTROL_DEVICE)
	stat_append " : ETH"
	/usr/sbin/chat -v "" "AT+CFUN=4" "OK" > $(CONTROL_DEVICE) < $(CONTROL_DEVICE)
	stat_append " : MODE"
	echo 0 > $RFKILL_DEVICE
	stat_append " : RFKILL"
	while [ -n "$(lsusb -d $USB_ID)" ] ; do sleep 0.5 ; done
    rm_daemon wwan
    stat_done
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
